name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Release Gem
      uses: cadwallion/publish-rubygems-action@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        RELEASE_COMMAND: rake release
